#!/bin/bash

echo "Default font size (in px): "
read size;
size=$(echo $size | sed 's/px//g') # Filter out px if added

em=$(bc <<< "scale=10; 1/$size")

echo
echo '==========================================='
echo '|    px    |      rem      |      %       |'

for i in {6..24}
  do
    curEm=$(bc <<< "scale=10; $em*$i")
    curPer=$(bc <<< "scale=10; $em*$i*100")
    printf "|  %2s" "$i"
    printf "%s\t" "px    |"
    printf "%.5s" "$curEm"
    printf "%s\t" "em    |"
    printf "%.5s" "$curPer"
    printf "%s\t\n" "%    |"
    i=$(($i+1))
  done
echo '============================================'
echo
