#!/bin/bash

echo "Base font size (in px): "
read base 
base=$(echo $base | sed 's/px//g') # Filter out px if added

echo "Size to convert (in px): "
read size
size=$(echo $size | sed 's/px//g') # Filter out px if added


unit=$(bc <<< "scale=10; 1/$base") 

converted=$(bc <<< "scale=10; $unit*$size")

echo "Converted size: $converted em"
