#!/bin/bash

usage()
{
    cat << EOF
webConversion
Description: simple tool to conver between rem, px, and %
Usage: ./pxtorem
Follow prompts for sizes: First, base px size, then size (in px) to convert

Alternatively arguments can be passed in as ./pxtorem 1 16

To view a table of sizes, run ./pxtables
EOF
}

while getopts 'vh' flag; do
  case "${flag}" in
    h) usage
       exit 0 ;;
    v) verbose='true' ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

if [[ $# == 2 ]]; then
    base=$1
    size=$2

else

	echo "Base font size (in px): "
	read base
	base=$(echo $base | sed 's/px//g') # Filter out px if added

	echo "Size to convert (in px): "
	read size
	size=$(echo $size | sed 's/px//g') # Filter out px if added

fi

unit=$(bc <<< "scale=10; 1/$base")

converted=$(bc <<< "scale=10; $unit*$size")

echo "Converted size: $converted rem"
