#!/bin/bash
#not complete
echo "Root element font size (in px): "
read root;

echo "Size to convert (to rem): "
read size;

unit=$(bc <<< "scale=10; 1/$root") 

converted=$(bc <<< "scale=10; $unit*$size")

echo "Converted size: $converted";
